---
- name: Download packer
  get_url:
    url: "{{ packer_download_url }}"
    dest: /tmp
    mode: '0644'

- name: Extract packer and mv to {{ packer_path }}
  unarchive:
    src: "{{ packer_zip_path }}"
    dest: "{{ packer_path }}"
