packer_version: 1.5.6
packer_download_url: 'https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip'
packer_zip_path: '/tmp/packer_{{ packer_version }}_linux_amd64.zip'
packer_path: /usr/local/bin
