---

#Ubuntu
- name: Install docker on Debian OS Family
  block:
    - name: Install prerequisites
      apt: name={{item}} update_cache=yes
      with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common

    - name: Add Docker GPG key
      apt_key: url= "{{ docker_gpgkey }}"

    - name: Add Docker APT repository
      apt_repository:
        repo: "{{ docker_repo }}"

    - name: Install Docker
      apt: name= "{{ docker_package_name }}"

  when: ansible_os_family == "Debian"


#CentOS
- name: Install docker on Redhat OS Family
  block:
    - name: Add Docker repo
      get_url:
        url: "{{ docker_repo_url }}"
        dest: "{{ docker_repo_path }}"

    - name: Install Docker
      package:
        name: "{{ docker_package_name }}"
        state: latest
  when: ansible_os_family == "Redhat"
